#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

/// Very careful when changing solution settings on where the path starts from

// Folder roots
#define FY_PROJECT_FOLDER_ROOT "../../../Frosty/"
#define FY_ASSETS_FOLDER_ROOT FY_PROJECT_FOLDER_ROOT "assets/"
#define FY_SHADERS_FOLDER_ROOT FY_ASSETS_FOLDER_ROOT "shaders/"

// Shaders
#define FY_SHADER_TESTSHAPE_VERTEX_SHADER FY_SHADERS_FOLDER_ROOT "TestShapeVertex.glsl"
#define FY_SHADER_TESTSHAPE_FRAGMENT_SHADER FY_SHADERS_FOLDER_ROOT "TestShapeFragment.glsl"
#define FY_SHADER_TESTLIGHT_VERTEX_SHADER FY_SHADERS_FOLDER_ROOT "TestLightVS.glsl"
#define FY_SHADER_TESTLIGHT_FRAGMENT_SHADER FY_SHADERS_FOLDER_ROOT "TestLightFS.glsl"
#define FY_SHADER_TESTTEXTURE_VERTEX_SHADER FY_SHADERS_FOLDER_ROOT "TestTextureVertex.glsl"
#define FY_SHADER_TESTTEXTURE_FRAGMENT_SHADER FY_SHADERS_FOLDER_ROOT "TestTextureFragment.glsl"
#endif // !DEFINITIONS_HPP
